version: 2
updates:
  # Enable version updates for Bun dependencies
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "vendor"
      include: "scope"
    labels:
      - "dependencies"
      - "vendor-update"
