# golangci-lint configuration file
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  skip-dirs:
    - frontend/dist

issues:
  exclude-dirs:
    - frontend/dist

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
