# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/ for details

# This file contains only configs which differ from defaults.
# All possible options can be found here https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

# Configuration file version
version: 2
run:
  timeout: 5m
  skip-dirs:
    - frontend/dist
  skip-files:
    - "frontend/dist/**/*"

issues:
  exclude-rules:
    - path: frontend/dist/.*
      linters:
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - ineffassign
        - gofmt
        - goimports

linters:
  enable-all: false
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
