// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function CreateNote(arg1:string):Promise<main.WailsNote>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetAllNotes():Promise<Array<main.WailsNote>>;

export function GetNote(arg1:string):Promise<main.WailsNote>;

export function GetSettings():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function IsPasswordSet():Promise<boolean>;

export function ResetApplication():Promise<void>;

export function SearchNotes(arg1:string):Promise<Array<main.WailsNote>>;

export function SetPassword(arg1:string):Promise<void>;

export function SyncFromDisk():Promise<void>;

export function UpdateNote(arg1:string,arg2:string):Promise<main.WailsNote>;

export function VerifyPassword(arg1:string):Promise<boolean>;
