// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function CompleteInitialSetup(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateBackup():Promise<string>;

export function CreateNote(arg1:string):Promise<main.WailsNote>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetAllNotes():Promise<Array<main.WailsNote>>;

export function GetNote(arg1:string):Promise<main.WailsNote>;

export function GetPerformanceStats():Promise<Record<string, any>>;

export function GetSecurityInfo():Promise<Record<string, any>>;

export function GetSettings():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function HandleError(arg1:Error):Promise<Record<string, any>>;

export function IsConfigured():Promise<boolean>;

export function IsPasswordSet():Promise<boolean>;

export function IsUsingSecureMethod():Promise<boolean>;

export function Logout():Promise<void>;

export function ResetApplication():Promise<void>;

export function SearchNotes(arg1:string):Promise<Array<main.WailsNote>>;

export function SetPassword(arg1:string):Promise<void>;

export function SyncFromDisk():Promise<void>;

export function UpdateNote(arg1:string,arg2:string):Promise<main.WailsNote>;

export function UpdateSettings(arg1:string,arg2:string):Promise<void>;

export function ValidateSetupInputs(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function VerifyPassword(arg1:string):Promise<boolean>;
